### ISSUE TITLE
Operator injection

### ISSUE THREAD

**Issue by mavam** [jarro2783/thenewcpp#14]
I was wondering whether we can inject relational operators into the variant whenever all types provide them. For example, the variant already provides `operator==`, but what about `operator<` and friends?

For all types `T` in the variant, we can use `decltype(std::declval<T>() < std::declval<T>())` to check whether the expression is valid, and if so, inject `operator<` for the variant via SFINAE.

Obviously this could be extended to arithmetic operators, but I think the relational ones are most useful.

**Comment by jarro2783** [comment]
This is no problem for the relational operators. It might be problematic for others, since it is unclear what they should return, although it might just be a binary visitor that should return the same value.

**Comment by jarro2783** [comment]
I have done this in the style of the proposal of the new `std::variant`. This issue is non-trivial as discussed in the proposal. Requiring operator< for all pairs of types is overly restrictive, and throwing at runtime is not desirable.

It might be an option to return false when something is non comparable. At the moment, I have implemented for each operator op, if op(v.which(), w.which()) or v.which() == w.which() && op(v.get(), w.get()) then true, else false.

This reqires that all types T in the variant have op(T, T) defined. However, what you have suggested might be possible, and if op(T, T) is not defined, then the result is false.
