### ISSUE TITLE
check the assumptions on types

### ISSUE THREAD

**Issue by vkhomenko** [jarro2783/thenewcpp#6]
Another suggestion: as we now have `is_nothrow_default_constructible` and `is_nothrow_move_constructible`, it would be nice to add a `static_assert` checking the assumptions about the types passed to `Variant`.

**Comment by jarro2783** [comment]
I think I'm going to take another approach which is to allow for the variant to be empty, as proposed for the standard version of variant. Then I don't need those restrictions, which are possibly overly restrictive. I don't know how good the compiler is at working out if something can't throw, or even how possible it is, since not throwing is equivalent to the halting problem. Even though usually we would probably say that moving doesn't allocate memory and shouldn't throw, the compiler might not be able to see that.
